# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  encoding: unicode
  pool: 5
  timeout: 5000

# Development needs a non-sqlite database because of the load that playing
# with real data gives.  Using sqlite was very slow.
development:
  <<: *default
  adapter: postgresql
  host: localhost
  database: reporting_dev
  username: reporting
  password: LofvuOwdOtocnadBedOg

# Use an sqlite database for ease of testing, since we won't load real data.
test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  host: localhost
  database: reporting
  username: reporting
  password: LofvuOwdOtocnadBedOg
